apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperlook
  namespace: monitoring
  labels:
    k8s-app: hyperlook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperlook
      k8s-app: hyperlook
  template:
    metadata:
      labels:
        app: hyperlook
        k8s-app: hyperlook
    spec:
      containers:
      - name: hyperlook
        image: hyperlook:latest
        args:
        - "--container-name=peer"
        - "--elastic-search-addr=elasticsearch-logging.kube-system"
        - "--elastic-search-port=9200"
        - "--elastic-search-size=200"
        - "--fabric-namespace=fabric-net"
        - "--interval=60"
        - "--listen-addr=0.0.0.0:2053"
        imagePullPolicy: Never
        ports:
        - name: hyperlook
          containerPort: 2053
      restartPolicy: Always

