apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hyperlook
  namespace: monitoring
  labels:
    k8s-app: hyperlook
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: hyperlook
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: hyperlook-metrics
    interval: 30s

